version: '3.8'

services:
  app:
    image: mdsumon12ir/ottomaxai:latest

    container_name: myapp

    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env

    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always